"""English translations for layer category names."""

CATEGORY_MAJOR_EN: dict[str, str] = {
    "A": "Traffic",
    "B": "Building",
    "C": "Facility",
    "D": "Vegetation",
    "E": "Water",
    "F": "Terrain",
    "G": "Boundary",
    "H": "Annotation",
}

CATEGORY_MID_EN: dict[str, str] = {
    # A — Traffic
    "교량": "Bridge",
    "교차로": "Intersection",
    "나루": "Ferry",
    "나루노선": "FerryRoute",
    "도로경계": "RoadBoundary",
    "도로중심선": "RoadCenterline",
    "안전지대": "SafetyZone",
    "육교": "Overpass",
    "인도(보도)": "Sidewalk",
    "인터체인지": "Interchange",
    "입체교차부": "GradeSeparation",
    "정거장": "Station",
    "정류장": "Stop",
    "철도": "Railway",
    "철도경계": "RailwayBoundary",
    "철도전차대": "RailwayTurntable",
    "철도중심선": "RailwayCenterline",
    "터널": "Tunnel",
    "터널입구": "TunnelEntrance",
    "플랫폼": "Platform",
    "플랫폼의 지붕": "PlatformRoof",
    "횡단보도": "Crosswalk",
    # B — Building
    "건물": "Building",
    "담장": "Wall",
    # C — Facility
    "게시판": "BulletinBoard",
    "계단": "Stairs",
    "공중전화": "PayPhone",
    "관정": "Well",
    "관측소": "Observatory",
    "광산": "Mine",
    "굴뚝": "Chimney",
    "낚시터": "FishingSpot",
    "놀이시설": "Playground",
    "댐": "Dam",
    "도로반사경": "RoadMirror",
    "도로분리대": "RoadMedian",
    "동상": "Statue",
    "등대": "Lighthouse",
    "맨홀": "Manhole",
    "묘지": "Cemetery",
    "묘지계": "CemeteryBoundary",
    "문화재": "CulturalHeritage",
    "방지책": "Barrier",
    "부두": "Wharf",
    "분수": "Fountain",
    "비석/기념비": "Monument",
    "선거": "Dock",
    "선착장": "Pier",
    "성": "Fortress",
    "소화전": "Hydrant",
    "수문": "Sluice",
    "신호등": "TrafficLight",
    "암거": "Culvert",
    "야영지": "Campsite",
    "양식장": "Fishery",
    "온천": "HotSpring",
    "요금징수소": "TollBooth",
    "우물/약수터": "SpringWell",
    "우체통": "Mailbox",
    "유적지": "HistoricSite",
    "잔교": "Jetty",
    "저장조": "StorageTank",
    "적치장": "Stockyard",
    "전력주/통신주": "UtilityPole",
    "제방": "Levee",
    "조명": "Lighting",
    "주유소": "GasStation",
    "주차장": "ParkingLot",
    "지하도": "Underpass",
    "지하도입구": "UnderpassEntrance",
    "지하환기구": "Ventilator",
    "차단기": "Gate",
    "채취장": "Quarry",
    "탑": "Tower",
    "탱크": "Tank",
    "표지": "Sign",
    "해수욕장": "Beach",
    "헬기장": "Helipad",
    "휴게소": "RestArea",
    # D — Vegetation
    "경지계": "FarmlandBoundary",
    "독립수": "IsolatedTree",
    "목장": "Pasture",
    "지류계": "TributaryBoundary",
    # E — Water
    "등심선": "DepthContour",
    "실폭하천": "Stream",
    "용수로": "WaterChannel",
    "유수방향": "FlowDirection",
    "폭포": "Waterfall",
    "하천경계": "RiverBoundary",
    "하천중심선": "RiverCenterline",
    "해안선": "Coastline",
    "호수/저수지": "Lake",
    # F — Terrain
    "동굴입구": "CaveEntrance",
    "등고선": "ContourLine",
    "성/절토": "Embankment",
    "옹벽": "RetainingWall",
    "표고점": "SpotHeight",
    # G — Boundary
    "기타경계": "OtherBoundary",
    "수부지형경계": "WaterBoundary",
    "행정경계": "AdminBoundary",
    # H — Annotation
    "격자": "Grid",
    "기준점": "ControlPoint",
    "도곽": "MapFrame",
    "산/산맥": "Mountain",
    "지명": "PlaceName",
}


def build_renamed(code: str, major: str, mid: str) -> str:
    """Build renamed layer name: {code}_{MajorEN}_{MidEN}."""
    major_en = CATEGORY_MAJOR_EN.get(major, "")
    mid_en = CATEGORY_MID_EN.get(mid, "")
    if major_en and mid_en:
        return f"{code}_{major_en}_{mid_en}"
    if major_en:
        return f"{code}_{major_en}"
    return code
